baseURL = "https://jayturpin.com/"
languageCode = "en-us"
title = "Jay Turpin"
theme = "congo"
defaultContentLanguage = "en"

[params]
  description = "Jay Turpin's Personal Blog"
  
  [params.author]
    name = "Jay Turpin"
    image = "JayTurpin-300x300.jpg"
    headline = "Software Engineer & Technology Enthusiast"
    links = [
      { github = "https://github.com/turp" },
      { twitter = "https://x.com/turp" },
      { linkedin = "https://www.linkedin.com/in/jayturpin/" },
      
    ]
  
  [params.homepage]
    layout = "page"
    showRecent = true
    
  [params.article]
    showDate = true
    showAuthor = true
    showBreadcrumbs = true
    showDraftLabel = true
    showEdit = false
    showReadingTime = true
    showTableOfContents = true
    showTaxonomies = true
    
  [params.header]
    layout = "basic"
    
  [params.footer]
    showCopyright = true
    showThemeAttribution = true
    showAppearanceSwitcher = true
  
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20
  [[menu.main]]
    identifier = "contributors"
    name = "Contributors"
    url = "/contributors/"
    weight = 20


    